# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  check-and-build-only:
    executor: docker-publish/machine
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: irisnet/irishub
orbs:
  docker: circleci/docker@0.1.0

version: 2.1
workflows:
  build-docker-image-only:
    jobs:
      - check-and-build-only:
          filters:
            branches:
              only:
                - master
                - develop
                - yelong/devops